coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  behavior: default
  hide_project_coverage: false
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: false
